name: "Godot 4 Lint Only"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GODOT_VERSION: 4.3

jobs:
  lint:
    name: GDScript lint
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:${GODOT_VERSION}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable \
             ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Lint
        run: |
          godot --headless --path . --doctool .

      - name: GDScript lint with gdlint
        run: |
          pip install gdlint
          gdlint --exclude=.github .
