name: "Godot 4 Lint Only"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: GDScript lint
    strategy:
      matrix:
        godot-version: [4.3]
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:${{ matrix.godot-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${{ matrix.godot-version }}.stable \
             ~/.local/share/godot/export_templates/${{ matrix.godot-version }}.stable

      - name: Lint
        run: |
          godot --headless --path . --doctool .

      - name: GDScript lint with gdlint
        run: |
          pip install "gdtoolkit==4.*"
          gdlint source/
